version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app    
    env_file:
      - ./.env    
    depends_on:
      - db        
    networks:
      - app-network

  db:
    image: mysql:8.0 
    ports:
      - "3307:3306" 
    env_file:
      - ./.env    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}       
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - app-network

volumes:
  db_data: 

networks:
  app-network:
    driver: bridge 